### ISSUE TITLE
7.1.x CE (debian) install and mariadb driver select error

### ISSUE THREAD

**Issue by pmenga52** [KnowageLabs/Knowage-Server#126]
**Describe the bug**
I tried CE installation on Debian and Ubuntu, (Knowage CE 7.0, 7.1.3 and 7.1.5). and the only way to correctly install databases is to choose MySQL driver (and not mariadb) even if the installed database is mariadb-server

I suppose the emmbeded mariadb driver is not corect (or the embedded settings)

**To Reproduce**
1. ./Knowage-7_1_5-CE-Installer-Unix-20200324.sh -c
2. answer a few questions, until "Use an already installed DBMS [1, Enter]"
3. Select DBMS for metadata: (choose MariaDB [1, Enter])
4. [jdbc:mariadb://localhost:3306] (press enter)
5. enter login and password
6. here is the beginning of error:

"20/04/09 08:54:05 INFO jdbc.Driver: Embedded Neo4j support not enabled org/neo4j/graphdb/GraphDatabaseService
20/04/09 08:54:05 INFO jdbc.Driver: Embedded Neo4j support not enabled org/neo4j/graphdb/GraphDatabaseService
java.lang.NoSuchMethodError: org.hsqldb.DatabaseURL.parseURL(Ljava/lang/String;ZZ)Lorg/hsqldb/persist/HsqlProperties;
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
..."

**Expected behavior**

If you choose MySQL driver at the installation, eveything is OK (even if the existing database is MariaDB)

**Desktop (please complete the following information):**
 - OS:debian 10.x (butler)
 - Browser firefox,chrome
 - Version 75

**Comment by kerny3d** [comment]
@pmenga52, from what i know, the MySQL JDBC driver shipped by the Knowage installer are compatible with MySQL and MariaDB, although you use `jdbc:mysql` and not `jdbc:mariadb`. Then i think you won't have any problem but i'll try to replicate your case anyway.

**Comment by josecsm** [comment]
I get the same error on Centos 7 with Maria DB 10.4.13  installed

**Comment by josecsm** [comment]
I get the error both choosing MySQL or mariadb

**Comment by kerny3d** [comment]
@pmenga52, @josecsm, which version of JDK do you use? OpenJDK or Oracle?

**Comment by josecsm** [comment]
I used both OpenJdk 8 and Oracle 8

**Comment by pmenga52** [comment]
I use openjdk-8-jdk-headless (8u252-b09-1~18.04) on ubuntu 18.04

**Comment by kerny3d** [comment]
Trying to replicate your case, I've created two new virtual machine with Vagrant, one with CentOS 7 and one with Debian 10: i cannot replicate your case on both machines.

Could you check if in your installation you have something related to Neo4j? I mean, could you check if your packet manager have installed some JARs related to Neo4j, for example, a newer version of the JDBC driver that is present in the system classpath? I think the problem could be related to something external to the installer.

**Comment by josecsm** [comment]
Hi, I have successfully installed the system. My workaround is:
1-Clean centos 7 install (form linode.com VPS)
2- Install Java Oracle 8_u251
3-Instal MariaDB 10.2 (not the latest one)
4-When installing select MySQL instead of (installed) MariaDB.

If you choose MariaDB driver (the one you installed) you can get the error.
If you install the last version of MariaDB you get the error no matter what
you choose (mysql or mariadb driver)
If you install the last unix version from the private section you get the
error no matter what you get

I attach two files of error log

**Comment by kerny3d** [comment]
On my last post I said Neo4J: i was wrong, it was HSQLDB.

@josecsm, that's a good news. I think the point is to have a "clean system".
