### ISSUE TITLE
Run knowage error

### ISSUE THREAD

**Issue by Hello-Linux** [KnowageLabs/Knowage-Server#162]
**Describe the bug**
the error log is
```
ERROR it.eng.spagobi.tools.dataset.service.SelfServiceDatasetAction.getParameters:156 - CacheException catched:
it.eng.spagobi.tools.dataset.cache.CacheException: An unexpected error occured while initializing cache
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheManager.initializeCache(SpagoBICacheManager.java:68)
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheManager.getCache(SpagoBICacheManager.java:44)
 at it.eng.spagobi.tools.dataset.service.SelfServiceDatasetAction.buildQbeEditFromFederationServiceUrl(SelfServiceDatasetAction.java:356)
 at it.eng.spagobi.tools.dataset.service.SelfServiceDatasetAction.getParameters(SelfServiceDatasetAction.java:110)
 at org.apache.jsp.WEB_002dINF.jsp.tools.catalogue.datasetManagement_jsp._jspService(datasetManagement_jsp.java:441)
 at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
 at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
 at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
 at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
 at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
 at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.
Caused by: it.eng.spagobi.utilities.exceptions.SpagoBIRuntimeException: An unexpected exception occured while loading cache datasource
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheConfiguration.getCacheDataSource(SpagoBICacheConfiguration.java:89)
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheConfiguration.getInstance(SpagoBICacheConfiguration.java:57)
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheManager.initializeCache(SpagoBICacheManager.java:57)
 ... 64 more
Caused by: it.eng.spagobi.utilities.exceptions.SpagoBIRuntimeException: Cannot configure cache: Data source for writing is not defined. Please select one in the data sources definition panel.
 at it.eng.spagobi.tools.dataset.cache.SpagoBICacheConfiguration.getCacheDataSource(SpagoBICacheConfiguration.java:84)
 ... 66 more
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcob1995** [comment]
Hi, steps to reproduce the issue are missing, so I don't know the scenario in which the error happened.
However from the logs it looks like your DataSource is not configured for writing.
Take a look at this [thread](https://github.com/KnowageLabs/Knowage-Server/issues/115)

**Comment by Hello-Linux** [comment]
Thank you very much! @marcob1995

**Comment by Hello-Linux** [comment]
@marcob1995  How to solve this problem?

**Comment by EddyeBoy27** [comment]
@Hello-Linux you solved this problem? This errors show when you startup? Or on Installation ?
