### ISSUE TITLE
using a Parameter in REST data set give an error

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server#222]
**Describe the bug**
defining a Parameter in REST data set give an error !
I have a working REST data set
I add a parameter to be used in the request url, 

but as soon I click "execute" in PREVIEW interface an error is returned, such as : 
even I use the parameter in the request such as `&dateFrom=$P{dateFrom}` or not,
just the fact to add a parameter, provokes the error in PREVIEW !

An error is also logged in knowage.log :

```
[http-nio-8080-exec-219] 09 Aug 2021 18:15:05,254 ERROR it.eng.spagobi.rest.interceptors.RestExceptionMapper.toResponse:59 - Catched service error: 
it.eng.spagobi.utilities.exceptions.SpagoBIServiceException: An unexpected error occured while executing dataset: java.lang.NullPointerException
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDatasetTestResultList(ManageDataSetsForREST.java:1789)
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDataSetResultsAsJSON(ManageDataSetsForREST.java:1737)
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.datasetTest(ManageDataSetsForREST.java:1696)
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.previewDataset(ManageDataSetsForREST.java:144)
        at it.eng.spagobi.api.DataSetResource.previewDataSet(DataSetResource.java:888)
        at sun.reflect.GeneratedMethodAccessor889.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at sun.reflect.GeneratedMethodAccessor307.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at it.eng.spagobi.tools.dataset.common.dataproxy.RESTDataProxy.replaceParameters(RESTDataProxy.java:269)
        at it.eng.spagobi.tools.dataset.common.dataproxy.RESTDataProxy.setParameters(RESTDataProxy.java:248)
        at it.eng.spagobi.tools.dataset.bo.ConfigurableDataSet.loadData(ConfigurableDataSet.java:102)
        at it.eng.spagobi.tools.dataset.bo.RESTDataSet.loadData(RESTDataSet.java:112)
        at it.eng.spagobi.tools.dataset.bo.ConfigurableDataSet.test(ConfigurableDataSet.java:210)
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDatasetTestResultList(ManageDataSetsForREST.java:1768)
        ... 65 more
```
**To Reproduce**

**Expected behavior**
adding a parameter should not generate an error....
and the parameter replaced in the query before sending it !

**Screenshots**
<img width="1373" alt="Capture d’écran 2021-08-09 à 20 58 36" src="https://user-images.githubusercontent.com/20285859/128759594-6dbab757-16f0-4783-b1ab-87855635fe68.png">

**Additional context**
occurs on Knowage community version 7.4.5

**Comment by kerny3d** [comment]
I confirm the error.

It will be fixed in 7.4.9 and 8.0.0.

**Comment by kerny3d** [comment]
Fixed in branch 7.4:

https://github.com/KnowageLabs/Knowage-Server/commit/cd357cb5143e7899ab5ee5061eab8ebc3b73b536

**Comment by agaldemas** [comment]
Hello, thanks @kerny3d !

I imagine the new dockerhub image should be available soon ?

@HugoT852, please to follow dockerhub image update !

**Comment by kerny3d** [comment]
Because of holidays we haven't scheduled the release of the 7.4.9 version yet.

**Comment by agaldemas** [comment]
Thanks for the update, we'll wait...

**Comment by agaldemas** [comment]
@kerny3d , little question : does this fix is or will be merged in master branch ?

**Comment by kerny3d** [comment]
It's already merged in master at:

https://github.com/KnowageLabs/Knowage-Server/commit/9d626bd8136fe6112681f23cc721979843d11191
