### ISSUE TITLE
Problem creating Metamodel with Postgres with JNDI datasource

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#35]
<p>As reported by a user on Q&A it seems that using a Postgres JNDI datasource the schema is not correctly retrieved and is set always to "public".</p>

<p>See also: <a href="https://www.knowage-suite.com/qa/530/how-to-set-up-multischema-postgresql-datasource-as-type-jndi" class="external-link" rel="nofollow">https://www.knowage-suite.com/qa/530/how-to-set-up-multischema-postgresql-datasource-as-type-jndi</a></p>
<i>[KNOW-65] created by mcortella</i>

**Comment by fuad022** [comment]
Hi, I created multischema data source using PostgreSQL. In Business Model Catalog I want to create Metamodel. And after clicking on the “META WEB”, I get errorbox: "Errors while attempting to load the datasource Error while getting structure of data source by id". Which of the solutions? With regards.

Error log: 

[http-bio-8080-exec-1] 05 Mar 2019 10:35:31,450 ERROR it.eng.spagobi.api.v2.DataSourceResource.getDataSourceStruct:332 - Error while getting structure of data source by id

java.lang.NullPointerException

at it.eng.spagobi.api.v2.DataSourceResource.getTableMetadata(DataSourceResource.java:397)

at it.eng.spagobi.api.v2.DataSourceResource.getDataSourceStruct(DataSourceResource.java:329)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)

at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)

at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)

at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)

at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)

at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409)

at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044)

at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)

at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)

at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.lang.Thread.run(Unknown Source)

[http-bio-8080-exec-1] 05 Mar 2019 10:35:31,451 ERROR it.eng.spagobi.rest.interceptors.RestExceptionMapper.toResponse:59 - Catched service error: 

it.eng.spagobi.utilities.exceptions.SpagoBIRestServiceException: Error while getting structure of data source by id

at it.eng.spagobi.api.v2.DataSourceResource.getDataSourceStruct(DataSourceResource.java:333)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)

at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)

at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)

at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)

at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)

at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409)

at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044)

at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)

at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)

at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.NullPointerException

at it.eng.spagobi.api.v2.DataSourceResource.getTableMetadata(DataSourceResource.java:397)

at it.eng.spagobi.api.v2.DataSourceResource.getDataSourceStruct(DataSourceResource.java:329)

... 33 more
![q2](https://user-images.githubusercontent.com/31619165/53790532-98787a00-3f40-11e9-8a3f-bd2776f4d1c5.jpg)
![q1](https://user-images.githubusercontent.com/31619165/53790549-9f9f8800-3f40-11e9-8785-e94a8601b8e4.jpg)

**Comment by mcortella** [comment]
Hi,
in the jndi resource definition of the server.xml you must set  factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" as stated here: https://knowage-suite.readthedocs.io/en/6.3/installation-guide/manual-installation.html#connection-to-business-data

**Comment by fuad022** [comment]
Hi,
I edited the `KNOWAGE_HOME/conf/server.xml` and add: 
`<Resource name="jdbc/mydatasource" 
          auth="Container"
          type="javax.sql.DataSource" 
          driverClassName="org.postgresql.Driver"
          url="jdbc:postgresql://xxxxx/xxxx"
          username="xxxx"
          password="xxxx" 
          maxWait="-1"
          maxActive="10"
          maxIdle="1"
          validationQuery="SELECT 1"
          removeAbandoned="true"
          removeAbandonedTimeout="3600"
          logAbandoned="true"
          testOnReturn="true"
          testWhileIdle="true"
          timeBetweenEvictionRunsMillis="10000"
          minEvictableIdleTimeMillis="60000"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" />`
and edit `webapps/all knowage*/META-INF/context.xml` :
`<ResourceLink global="jdbc/mydatasource" name="jdbc/mydatasource" type="javax.sql.DataSource"/>`,
but I still get the same error. Also in documentation [https://knowage-suite.readthedocs.io/en/6.3/administrator-guide/configure-data-sources.html?highlight=multischema#connect-to-your-data](url) If the data source is multischema, then the string is `java:comp/env/jdbc/<prefix>`. Where I can find this `prefix` name?

**Comment by fuad022** [comment]
Hi, I have another question. I created data sources of schemas which have their own username and password with jndi connection. 

![sch](https://user-images.githubusercontent.com/31619165/54356993-68368700-4676-11e9-85b6-baad68637ea2.jpg)

And defined in server.xml 

![res](https://user-images.githubusercontent.com/31619165/54357557-c879f880-4677-11e9-9120-810bf2db8eea.jpg)

And defined in context.xml:

`<ResourceLink global="jdbc/ds_schema1" name="jdbc/ds_schema1" type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/ds_schema2" name="jdbc/ds_schema2" type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/ds_schema3" name="jdbc/ds_schema3" type="javax.sql.DataSource"/>
<ResourceLink global="jdbc/ds_schema4" name="jdbc/ds_schema4" type="javax.sql.DataSource"/>`

I want to combine these schemas and then I created data source for multischema:

![comb](https://user-images.githubusercontent.com/31619165/54358346-95d0ff80-4679-11e9-8736-218b3b7e7dd8.jpg)

Where in "Jndi Name" I wrote `java:comp/env/jdbc/ds_`. `ds_` is prefix of schemas name from resource tag in server.xml . But when I click on "Test" button for check connection I get error:

![err](https://user-images.githubusercontent.com/31619165/54358907-e432ce00-467a-11e9-95b7-4ded59cc0ae7.jpg)

Error log:

```[http-bio-8080-exec-3] 14 Mar 2019 17:00:41,442 ERROR it.eng.spagobi.tools.datasource.service.rest.TestConnection.testDataSourceNew:200 - Error testing datasources
javax.naming.NameNotFoundException: Name [ds_] is not bound in this Context. Unable to find [ds_].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:820)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:168)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:158)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at it.eng.spagobi.tools.datasource.service.rest.TestConnection.testDataSourceNew(TestConnection.java:157)
	at sun.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Where do i make a mistake? Or where I must add some code or operation? 
Can You help me?

**Comment by roneijcosta** [comment]
I have a similar error: 

Errors while attempting to load the datasource
HTTP Status 500 – Internal Server Error
HTTP Status 500 – Internal Server Error
Type Exception Report

Message java.lang.RuntimeException: Impossible to initialize physical model

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Impossible to initialize physical model
	org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
	org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
	org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:171)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:414)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.RuntimeException: Impossible to initialize physical model
	it.eng.knowage.meta.initializer.PhysicalModelInitializer.initialize(PhysicalModelInitializer.java:261)
	it.eng.knowage.meta.service.MetaService.createEmptyModel(MetaService.java:1652)
	it.eng.knowage.meta.service.MetaService.createModels(MetaService.java:164)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.RuntimeException: Impossible to initialize schema metadata
	it.eng.knowage.meta.initializer.PhysicalModelInitializer.addSchema(PhysicalModelInitializer.java:365)
	it.eng.knowage.meta.initializer.PhysicalModelInitializer.initialize(PhysicalModelInitializer.java:169)
	it.eng.knowage.meta.service.MetaService.createEmptyModel(MetaService.java:1652)
	it.eng.knowage.meta.service.MetaService.createModels(MetaService.java:164)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.RuntimeException: No schema named [null] is available on db
	it.eng.knowage.meta.initializer.PhysicalModelInitializer.addSchema(PhysicalModelInitializer.java:358)
	it.eng.knowage.meta.initializer.PhysicalModelInitializer.initialize(PhysicalModelInitializer.java:169)
	it.eng.knowage.meta.service.MetaService.createEmptyModel(MetaService.java:1652)
	it.eng.knowage.meta.service.MetaService.createModels(MetaService.java:164)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.43
