### ISSUE TITLE
unable to save Geo-referenced analysis document

### ISSUE THREAD

**Issue by Thesyos** [KnowageLabs/Knowage-Server#681]
When Clicking on button "save", the popup Server error appears.

**To Reproduce**
1. Go to My Workspace > My Analysis 
2. Click on the "+" button at the top right corner > Geo-referenced analysis
3. For the Dataset section, click "add dataset" and select a dataset
4. For the Layer section, click "add layer" and select a layer
5. click on the "Dataset Join" tab > Add join column > add the mapping column
6. click on the "Indicator" tab > Add join column > add a measure column and a label
7. click save button on the top right corner
8. Add a label and a description, then click Save

**Expected behavior**
The Gis-report is saved with no error

**Screenshots**
The error
![image](https://user-images.githubusercontent.com/116186668/196729909-892d5c14-91c1-484d-9b6b-7738ca90d17b.png)

The dataset : 
![image](https://user-images.githubusercontent.com/116186668/196730330-4e757fe1-4676-43fc-8c85-954676305e04.png)
![image](https://user-images.githubusercontent.com/116186668/196730377-455f4de1-958c-4f98-80d1-5bfe6a85a4ff.png)
![image](https://user-images.githubusercontent.com/116186668/196730436-b3f16e5e-bb59-4dd4-9b9d-65484b026331.png)
![image](https://user-images.githubusercontent.com/116186668/196730514-b32083a6-99c2-4935-8e6e-014c2fdf20bf.png)

The layer : 
![image](https://user-images.githubusercontent.com/116186668/196730616-90f169db-6d95-4055-8b63-6213ab2fabd3.png)

the geojson file  : 
[francereg.zip](https://github.com/KnowageLabs/Knowage-Server/files/9821713/francereg.zip)

sql queries use to create and fill the table used by the dataset (postgresql)
[req.zip](https://github.com/KnowageLabs/Knowage-Server/files/9821719/req.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 106.0.5249.119

**Additional context**
To reproduce the issue : 
run the sql script to create and fill the table in postgresql
in knowage CE : 
1. Create a data source that references your database in postgresql
2. Create a flat dataset that references the table you just created
3. create a layer using the geojson file
4. create a Geo-referenced analysis document

**Comment by Thesyos** [comment]
For the records, here is the log : 

2022-10-24T09:31:08,404+00:00 [87286646-1c8b-4b20-8a1a-d827e15d297f] ERROR [http-nio-8080-exec-1] [it.eng.spagobi.rest.interceptors.RestExceptionMapper.toResponse:60] [f0e35a63-3dff-442e-b53b-2530febb2388] [] [DEFAULT_TENANT]
Catched service error: 
it.eng.spagobi.utilities.exceptions.SpagoBIServiceException: sbi.document.saveError
	at it.eng.spagobi.analiticalmodel.execution.service.v2.SaveDocumentResource.saveDocument(SaveDocumentResource.java:126) ~[knowage-core-8.1.0.jar:8.1.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at jdk.internal.reflect.GeneratedMethodAccessor487.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.50]
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:222) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:146) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) ~[catalina.jar:9.0.50]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.50]
	at jdk.internal.reflect.GeneratedMethodAccessor434.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.50]
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:188) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:146) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) ~[catalina.jar:9.0.50]
	at it.eng.knowage.utils.filters.LoggerSetupFilter.doFilter(LoggerSetupFilter.java:45) ~[knowage-utils-8.1.0.jar:8.1.0]
	at jdk.internal.reflect.GeneratedMethodAccessor434.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.50]
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:188) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:146) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) ~[catalina.jar:9.0.50]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.17.1.jar:2.17.1]
	at jdk.internal.reflect.GeneratedMethodAccessor434.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:550) ~[?:?]
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.50]
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:188) ~[catalina.jar:9.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:146) ~[catalina.jar:9.0.50]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [catalina.jar:9.0.50]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.50]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.50]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:9.0.50]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:9.0.50]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.50]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.50]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.50]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [catalina.jar:9.0.50]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-coyote.jar:9.0.50]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.50]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-coyote.jar:9.0.50]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) [tomcat-coyote.jar:9.0.50]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.50]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.50]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at it.eng.spagobi.analiticalmodel.execution.service.v2.SaveDocumentResource.checkAndSanitizeXSS(SaveDocumentResource.java:139) ~[knowage-core-8.1.0.jar:8.1.0]
	at it.eng.spagobi.analiticalmodel.execution.service.v2.SaveDocumentResource.saveDocument(SaveDocumentResource.java:102) ~[knowage-core-8.1.0.jar:8.1.0]
	... 90 more

**Comment by Thesyos** [comment]
Be aware that the error is reproduced in Knowage CE 8.1.0 and 8.1.1.
Can someone help on this??
