### ISSUE TITLE
Error while creating Data source for multischema

### ISSUE THREAD

**Issue by fuad022** [KnowageLabs/Knowage-Server#78]
Hi, I have another question. I created data sources of schemas which have their own username and password with jndi connection.

![sch](https://user-images.githubusercontent.com/31619165/54362109-ccab1380-4681-11e9-858f-388b567ce304.jpg)

And defined in server.xml

![res](https://user-images.githubusercontent.com/31619165/54362156-e187a700-4681-11e9-9f10-e9b1a49e6561.jpg)

And defined in context.xml:

`<ResourceLink global="jdbc/ds_schema1" name="jdbc/ds_schema1" type="javax.sql.DataSource"/> <ResourceLink global="jdbc/ds_schema2" name="jdbc/ds_schema2" type="javax.sql.DataSource"/> <ResourceLink global="jdbc/ds_schema3" name="jdbc/ds_schema3" type="javax.sql.DataSource"/> <ResourceLink global="jdbc/ds_schema4" name="jdbc/ds_schema4" type="javax.sql.DataSource"/>`

I want to combine these schemas and then I created data source for multischema:

![comb](https://user-images.githubusercontent.com/31619165/54362254-08de7400-4682-11e9-95de-d824f938a732.jpg)

In "Jndi Name" I wrote `java:comp/env/jdbc/ds_`, where `ds_` is prefix of schemas name from resource tag in server.xml . But when I click on "Test" button for check connection I get error:

![err](https://user-images.githubusercontent.com/31619165/54362335-2f9caa80-4682-11e9-8d4c-917cd72f01a2.jpg)

Error log:

```
[http-bio-8080-exec-3] 14 Mar 2019 17:00:41,442 ERROR it.eng.spagobi.tools.datasource.service.rest.TestConnection.testDataSourceNew:200 - Error testing datasources
javax.naming.NameNotFoundException: Name [ds_] is not bound in this Context. Unable to find [ds_].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:820)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:168)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:158)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at it.eng.spagobi.tools.datasource.service.rest.TestConnection.testDataSourceNew(TestConnection.java:157)
	at sun.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Where do i make a mistake? Or where I must add some code or operation for combine these schemas for retrieve tables from these schemas?
Can anyone help me?

**Comment by lstreamDave** [comment]
Hi. 
I think you missed setting the value of "company" for the user that is logged in.  I may be wrong, I'm new to Knowage, but in my testing, I noticed that the value of the attribute named under the MultiSchema item was appended to the JNDI name.  In the error message, it says "Unable to find [ds_]." which is what leads me to think the value was not set, since this is the same as the end of the JNDI name.
Good luck, hope this helps.

**Comment by fuad022** [comment]
> Hi.
> I think you missed setting the value of "company" for the user that is logged in. I may be wrong, I'm new to Knowage, but in my testing, I noticed that the value of the attribute named under the MultiSchema item was appended to the JNDI name. In the error message, it says "Unable to find [ds_]." which is what leads me to think the value was not set, since this is the same as the end of the JNDI name.
> Good luck, hope this helps.

Hi, thanks for your answer. I also defined in `KNOWAGE_SERVER_HOME/conf/server.xml`:
```
<Resource name="jdbc/ds_" auth="Container"
          type="javax.sql.DataSource" 
          driverClassName="org.postgresql.Driver"
          url="jdbc:postgresql://xxxxxxxx/xxx"
          username="root_username"
          password="root_pass" 
          maxWait="-1"
          maxActive="10"
          maxIdle="1"
          validationQuery="SELECT 1"
          removeAbandoned="true"
          removeAbandonedTimeout="3600"
          logAbandoned="true"
          testOnReturn="true"
          testWhileIdle="true"
          timeBetweenEvictionRunsMillis="10000"
          minEvictableIdleTimeMillis="60000"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" />
```
and in `all knowage*/META-INF/context.xml`:
`<ResourceLink global="jdbc/ds_" name="jdbc/ds_" type="javax.sql.DataSource"/>`

"Test" button in `CombineSchemas` works for this:

![comb](https://user-images.githubusercontent.com/31619165/55533223-9f221a80-56c1-11e9-9b45-bb4ef260f378.jpg)

Then I create in `Business models catalog`: 

![combine](https://user-images.githubusercontent.com/31619165/55533448-5fa7fe00-56c2-11e9-9a07-3395613e6952.jpg)

When I click on "Meta Web" button for retrieve these tables of schemas like this:

![44](https://user-images.githubusercontent.com/31619165/55533616-eceb5280-56c2-11e9-8e9e-2cef39a4f06b.jpg)

 I get error:

![q1](https://user-images.githubusercontent.com/31619165/55533663-1310f280-56c3-11e9-84bb-582a803f29b9.jpg)
What is the problem and where I must setting the value of "company"?

**Comment by lstreamDave** [comment]
Ok, here's what I think you need. As I said, I'm new, so I may be wrong, but I'm going to try.
First, "company" needs to defined in the "Profile Attributes" from the main menu, like this
![image](https://user-images.githubusercontent.com/13387441/55562646-3cbd2000-56a9-11e9-8798-397740e36757.png)

Then in the user's profile, it is given a value, like so.
![image](https://user-images.githubusercontent.com/13387441/55562770-7db53480-56a9-11e9-9f18-a27cd2860462.png)

I would log out the user and log in again to be sure it is seen, and then try your tests.  If you look at the error log (if it fails :-) ), you should be able to see where the string was appended.
Good luck.
