### ISSUE TITLE
error installing knowage - linux ubuntu 16.04

### ISSUE THREAD

**Issue by lwhitehead1706** [KnowageLabs/Knowage-Server#90]
Exception:

java.lang.NoSuchMethodError: org.hsqldb.DatabaseURL.parseURL(Ljava/lang/String;ZZ)Lorg/hsqldb/persist/HsqlProperties;
        at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
        at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.install4j.runtime.installer.helper.Install4jClassLoader$CustomCodeInvoker.invoke(Install4jClassLoader.java:165)
        at com.install4j.runtime.installer.helper.Install4jClassLoader.invokeInCustomClassLoader(Install4jClassLoader.java:156)
        at com.install4j.runtime.beans.actions.jdbc.AbstractJdbcAction.createConnection(AbstractJdbcAction.java:139)
        at com.install4j.runtime.beans.actions.jdbc.AbstractJdbcAction.withConnection(AbstractJdbcAction.java:201)
        at com.install4j.runtime.beans.actions.jdbc.AbstractJdbcAction.withStatement(AbstractJdbcAction.java:176)
        at com.install4j.runtime.beans.actions.jdbc.AbstractJdbcAction.withResultSet(AbstractJdbcAction.java:153)
        at com.install4j.runtime.beans.actions.jdbc.CheckJdbcConnectionAction.executeJdbcCall(CheckJdbcConnectionAction.java:32)
        at com.install4j.runtime.beans.actions.jdbc.AbstractJdbcAction.execute(AbstractJdbcAction.java:95)
        at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(SystemInstallOrUninstallAction.java:29)
        at com.install4j.runtime.installer.ContextImpl$7.executeAction(ContextImpl.java:1668)
        at com.install4j.runtime.installer.ContextImpl$7.fetchValue(ContextImpl.java:1659)
        at com.install4j.runtime.installer.ContextImpl$7.fetchValue(ContextImpl.java:1656)
        at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(FetchObjectAction.java:14)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionDirect(HelperCommunication.java:274)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(HelperCommunication.java:249)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionChecked(HelperCommunication.java:187)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.fetchObjectChecked(HelperCommunication.java:170)
        at com.install4j.runtime.installer.ContextImpl.performActionIntStatic(ContextImpl.java:1656)
        at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(InstallerContextImpl.java:151)
        at com.install4j.runtime.installer.ContextImpl.performAction(ContextImpl.java:1103)
        at com.install4j.runtime.installer.controller.Controller.executeAction(Controller.java:368)
        at com.install4j.runtime.installer.controller.Controller.executeActions(Controller.java:334)
        at com.install4j.runtime.installer.controller.Controller.handleCommand(Controller.java:195)
        at com.install4j.runtime.installer.controller.Controller.start(Controller.java:94)
        at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:59)
        at com.install4j.runtime.installer.Installer.main(Installer.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

System properties:

java.runtime.name=Java(TM) SE Runtime Environment
exe4j.moduleName=/home/user/Knowage-6_4_1-CE-Installer-Unix-20190605.sh
sun.boot.library.path=/usr/lib/jvm/jdk1.8.0_221/jre/lib/amd64
java.vm.version=25.221-b11
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
install4j.exeDir=/home/user/
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/home/user/Knowage-6_4_1-CE-Installer-Unix-20190605.sh.42810.dir
java.runtime.version=1.8.0_221-b11
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
i4jv=0
java.endorsed.dirs=/usr/lib/jvm/jdk1.8.0_221/jre/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

java.vm.specification.vendor=Oracle Corporation
os.name=Linux
exe4j.totalDataLength=2008302981
sun.java2d.noddraw=true
sun.jnu.encoding=UTF-8
java.library.path=/home/user/Knowage-6_4_1-CE-Installer-Unix-20190605.sh.42810.dir/user::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=4.4.0-157-generic
i4j.vpt=true
install4j.cwd=/home/user
user.home=/root
user.timezone=America/Los_Angeles
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
install4j.jvmDir=/usr/lib/jvm/jdk1.8.0_221
java.specification.version=1.8
java.class.path=i4jruntime.jar
user.name=root
java.vm.specification.version=1.8
sun.java.command=com.install4j.runtime.launcher.UnixLauncher launch 0   com.install4j.runtime.installer.Installer -c
java.home=/usr/lib/jvm/jdk1.8.0_221/jre
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_221
java.ext.dirs=/usr/lib/jvm/jdk1.8.0_221/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/usr/lib/jvm/jdk1.8.0_221/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/rt.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_221/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_221/jre/classes
java.awt.headless=true
install4j.appDir=/home/user/
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.font.fontmanager=sun.awt.X11FontManager
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
install4j.showProxyConfig=true
install4j.systemLanguage=en
install4j.keepLog=true
sun.cpu.isalist=
root@ubuntu:/home/user# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by xylo** [comment]
I get the same error on
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by lwhitehead1706** [comment]
> I get the same error on
> 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.2 LTS
> Release:        18.04
> Codename:       bionic
> ```
> 
> I don't get it. I selected MariaDB, but the installer is looking for a HSQLDB class.

yeah for some reason isn't looking for the correct driver, doesn't matter if you choose mariadb or mysql

**Comment by kholis** [comment]
any fix for this issue?

**Comment by EddyeBoy27** [comment]
I don't understand all the problem, but I think its around installation, right?
Well, I had some problems during installation, using Ubuntu 18.04 LTS too.
Basically, I had the first problem with JAVA_HOME environment variable, I set in .bash_profile and on / etc / environment
The documentation use a deprecated ppa about JDK 1.8 too, attention for this, JDK and openJDK are different, but the use of openJDK can't cause errors, just because openJDK have just more libs.
Firstly, I do 'sudo ./Knowage.....sh' on terminal, because the knowage installer needs a user privileges, but anyway, the installer doesn't find JAVA_HOME environment variable, I really don't know why, because when I write 'echo $ JAVA_HOME' on terminal, It shows to me the path where JDK are installed.
I tried 'sudo su' for enter in root user, and when I write "echo $ JAVA_HOME" in root user, the path doesn't exist. With this, I set the variable manually. 'export JAVA_HOME = pwd_of_your_jdk_installation'. Usually JDK or openJDK are installed in '/usr/lib/jvm-or-java/jdkX.X.X_XXX/'
After set the JAVA_HOME environment variables, I do the same for PATH, 'export PATH = $ JAVA_HOME / bin: $ PATH'
Either one or the other without single quotes.
After set the JAVA_HOME and PATH environment variables, I run the Knowage Installer, still inside root user, 'sudo su'.

With this I finished the installation, but I noticed that some database connectors come by default with some older versions of Knowage supported databases.
Look how is your Database Version and search on google the connector for your database version, you can search like: "Database name + JDBC or JNDI connector".

I hope this can help you with the same mistakes that I had .

**Comment by kholis** [comment]
It is because of duplicate of `hsqldb.jar` in installer classpath. 

**Workaround:**

1. Run installer as normal
2. Right before config RDBMS steps. 
```
Database Management System Configuration
Use an already installed DBMS [1, Enter]
1
Select DBMS for metadata:
MariaDB [1, Enter]
MySQL [2]
```

3. Open other terminal then Delete `hsqldb.jar` in temporary extracted installer dir (in my case: `/home/apps/Knowage-7_2_0-CE-Installer-Unix-20200730.sh.14611.dir`)

```
rm /home/apps/Knowage-7_2_0-CE-Installer-Unix-20200730.sh.14611.dir/user/hsqldb.jar
```

4. Continue installation
