### ISSUE TITLE
NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].

### ISSUE THREAD

**Issue by xylo** [KnowageLabs/Knowage-Server#93]
**Describe the bug**
I followed the manual installation guide, but the knowage webapp crashes with the following exception on start:
```
05-Aug-2019 10:59:41.097 WARNUNG [http-nio-8080-exec-6] org.apache.catalina.deploy.NamingResourcesImpl.cleanUp Failed to retrieve JNDI naming context for container [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/knowage]] so no cleanup was performed for that container
 javax.naming.NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].
        at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
        at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1020)
        at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1002)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5488)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:142)
        at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1377)
        at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:218)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**To Reproduce**
1. Set up a mysql database for knowage
2. Follow the steps on https://knowage-suite.readthedocs.io/en/6.4/installation-guide/manual-installation.html
3. Restart tomcat

**Expected behavior**
I expect knowage to start without exception.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Firefox 68.0.1 (64-Bit)
 - Version: 6.4.3 as well as
```
# git log -n 1
commit d6661421b54f46e460b7e5cfbba65a713330c334 (HEAD -> master, origin/master, origin/HEAD)
Author: Dragan Pirkovic <dragan.pirkovic@eng.it>
Date:   Fri Aug 2 10:32:43 2019 +0200

    [Bug closed] KNOWAGE-4222

# git rev-list --count HEAD
13649
```

**Comment by mcortella** [comment]
I suggest to build the web application from a tag, ie: https://github.com/KnowageLabs/Knowage-Server/tree/v6.4.3 because the master is not considered to be stable in every moment.

**Comment by xylo** [comment]
OK. Thanks.

**Comment by mcortella** [comment]
You can also find the binaries here, without having to manually build: https://release.ow2.org/knowage/6.4.2/Applications/

**Comment by xylo** [comment]
Unfortunately I get the same error when I use version 6.4.3.

**Comment by mcortella** [comment]
Can you please copy your server.xml's GlobalNamingResources, and context.xml of knowage ?

**Comment by xylo** [comment]
context.xml of knowage:
```
<Context path="/knowage" >
<!--	<Loader delegate="true"/>  -->
    <ResourceLink global="jdbc/foodmart_oracle" name="jdbc/foodmart_oracle" type="javax.sql.DataSource"/>
    <ResourceLink global="jdbc/IsoMedDB" name="jdbc/IsoMedDB" type="javax.sql.DataSource"/>
    <ResourceLink global="jdbc/foodmart_demo" name="jdbc/foodmart_demo" type="javax.sql.DataSource" />
	<ResourceLink global="jdbc/knowage" name="jdbc/knowage" type="javax.sql.DataSource"/>
	<ResourceLink global="jdbc/ds_cache" name="jdbc/ds_cache" type="javax.sql.DataSource"/>
	<ResourceLink global="resource_path" name="resource_path" type="java.lang.String" />
	<ResourceLink global="sso_class" name="sso_class" type="java.lang.String" />
	<ResourceLink name="hmacKey" global="hmacKey" type="java.lang.String"/>
	<ResourceLink global="host_url" name="host_url" type="java.lang.String" />
	<ResourceLink global="service_url" name="service_url" type="java.lang.String"/>
	<ResourceLink global="wm/SpagoWorkManager" name="wm/SpagoWorkManager" type="commonj.work.WorkManager" factory="de.myfoo.commonj.work.FooWorkManagerFactory"/>
</Context>
```

server.xml's GlobalNamingResources:
```
  <GlobalNamingResources>
    <!-- Editable user database that can also be used by
         UserDatabaseRealm to authenticate users
    -->
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
	      pathname="conf/tomcat-users.xml" />
    <Resource auth="Container"
              driverClassName="com.mysql.jdbc.Driver"
              name="jdbc/knowage"
              password="XXXXXXXX"
              type="javax.sql.DataSource"
              url="jdbc:mysql://localhost:3306/knowage"
              username="knowage"
              maxActive="10"
              maxIdle="1"
              validationQuery="select 1 = 1"
              removeAbandoned="true"
              removeAbandonedTimeout="3600"
              logAbandoned="true"
              testOnReturn="true"
              testWhileIdle="true"
              timeBetweenEvictionRunsMillis="10000"
	      minEvictableIdleTimeMillis="60000" />
    <Resource auth="Container"
              driverClassName="com.mysql.jdbc.Driver"
              name="jdbc/ds_cache"
              password="XXXXXXXX"
              type="javax.sql.DataSource"
              url="jdbc:mysql://localhost:3306/knowage_cache"
              username="knowage"
              maxActive="10"
              maxIdle="1"
              validationQuery="select 1 = 1"
              removeAbandoned="true"
              removeAbandonedTimeout="3600"
              logAbandoned="true"
              testOnReturn="true"
              testWhileIdle="true"
              timeBetweenEvictionRunsMillis="10000"
	      minEvictableIdleTimeMillis="60000" />
    <Resource auth="Container"
              driverClassName="com.mysql.jdbc.Driver"
              name="jdbc/IsoMedDB"
              password="XXXXXXXX"
              type="javax.sql.DataSource"
              url="jdbc:mysql://localhost:3306/IsoMedDB"
              username="IsoMedDB"
              maxWait="-1"
              maxActive="10"
              maxIdle="1"
              validationQuery="select 1 = 1"
              removeAbandoned="true"
              removeAbandonedTimeout="3600"
              logAbandoned="true"
              testOnReturn="true"
              testWhileIdle="true"
              timeBetweenEvictionRunsMillis="10000"
              minEvictableIdleTimeMillis="60000"
	      factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" />

    <Environment name="resource_path" type="java.lang.String" value="${catalina.home}/resources"/>
    <Environment name="sso_class" type="java.lang.String" value="it.eng.spagobi.services.common.JWTSsoService"/>
    <Environment name="service_url" type="java.lang.String" value="http://localhost:8080/knowage"/>
    <Environment name="host_url" type="java.lang.String" value="http://localhost:8080/knowage"/>
    <Environment description="HMAC key" name="hmacKey" type="java.lang.String" value="aeFies5t Lahghe4M quoiCu5Y"/>

    <Resource auth="Container" factory="de.myfoo.commonj.work.FooWorkManagerFactory" maxThreads="5" name="wm/SpagoWorkManager" type="commonj.work.WorkManager"/>
  </GlobalNamingResources>
```

**Comment by mcortella** [comment]
They seems fine for what I see. Is the context.xml inside the META-INF of the web application? What version of Tomcat are you using?

**Comment by xylo** [comment]
Yes, it's in META-INF.  And all other knowage webapps started without exceptions.  I'm using tomcat 8.5.39 installed via ubuntu apt.

**Comment by mcortella** [comment]
I suggest to try to install tomcat using the files provided directly by the tomcat website (https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.39/bin/), sometimes using apt the libraries are built from other repositories and cause problems.

**Comment by xylo** [comment]
OK.

**Comment by xylo** [comment]
You were right.  The manual tomcat installation did the trick. :) Thanks.
